# Copyright (c) Christopher Marget, 2024-2024.
# SPDX-License-Identifier: MIT
# Copyright (c) Juniper Networks, Inc., 2024-2024.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

---
name: Check For License Headers

on: [push]

jobs:
  license-header-check:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: fetch main
        run: |
          git fetch origin main

      - name: unshallow
        run: |
          git pull --unshallow

      - name: license header check
        run: |
          .ci/scripts/license_header_check.sh
